/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabla;



import javax.swing.JOptionPane;
import tabla.Tablero;

/**
 *
 * @author aaron
 */
public class ConfigurarJuego extends javax.swing.JFrame {

    private int n=0, nf=0;
    private int njugadores=0, nfichas=0;
    private final int puerto=5002;
    
    /**
     * Creates new form Prueva
     */
    public ConfigurarJuego(){
        initComponents();
        cmbJugadores.addItem("2");
        cmbJugadores.addItem("3");
        cmbJugadores.addItem("4");
        ///////////////////////////////////////////
        cmbFichas.addItem("2");
        cmbFichas.addItem("3");
        cmbFichas.addItem("4");
        cmbFichas.addItem("5");
        cmbFichas.addItem("6");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUnirse = new javax.swing.JButton();
        cmbJugadores = new javax.swing.JComboBox<>();
        txtApuesta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbFichas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Jugaores");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, 40));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(211, 83, 54));
        jLabel3.setText("Patolli");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 39));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fichas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 120, 50));

        btnUnirse.setText("Jugar");
        btnUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 120, 30));

        cmbJugadores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbJugadoresItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 110, 30));
        getContentPane().add(txtApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 110, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apuesta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 120, 50));

        cmbFichas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFichasItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 110, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoo.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseActionPerformed
    
        Tablero a = new Tablero();
        if(txtApuesta.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Fondo vacio, Ingrese fondo");
        }else{
            if(validarNumero(txtApuesta.getText())){
                int fondo=Integer.parseInt(txtApuesta.getText());
                a.recibirDatos(njugadores, fondo, nfichas);
                System.out.println("numero de jugadores "+njugadores+" Numero fichas "+nfichas);
                System.out.println("Fondooo" + fondo);
                a.show();
                ServerConfigJuego configJuego = new ServerConfigJuego(puerto, fondo, njugadores, nfichas);
                
            }else{
                JOptionPane.showMessageDialog(this, "Error! no es un numero, Ingrese solo numeros");
            }
            
        }
        
    }//GEN-LAST:event_btnUnirseActionPerformed

    private void cmbJugadoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbJugadoresItemStateChanged

        n = cmbJugadores.getSelectedIndex(); 
        System.out.println("que paso 1 "+n);
        NumeroJugadores();
    }//GEN-LAST:event_cmbJugadoresItemStateChanged

    private void cmbFichasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFichasItemStateChanged
           nf = cmbFichas.getSelectedIndex();
           System.out.println("que paso 1 "+nf+"--------");
           NumeroFichas();
    }//GEN-LAST:event_cmbFichasItemStateChanged

    public void NumeroJugadores(){       
            njugadores = Integer.parseInt(cmbJugadores.getItemAt(n));
            System.out.println("que paso 2"+njugadores);
    }
    
    public void NumeroFichas(){       
            nfichas = Integer.parseInt(cmbFichas.getItemAt(nf));
            System.out.println("que paso 2 "+nfichas+" -----------------");
    }
    
    public boolean validarNumero(String numero){
        try{
            Integer.parseInt(txtApuesta.getText());
            return true;
        }catch(Exception e){
            return false;
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigurarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigurarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigurarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigurarJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {             
                    new ConfigurarJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnirse;
    private javax.swing.JComboBox<String> cmbFichas;
    private javax.swing.JComboBox<String> cmbJugadores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtApuesta;
    // End of variables declaration//GEN-END:variables
}
